name: ESLint CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Node.js 環境をセットアップ
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 依存関係のインストール
      - name: Install dependencies
        run: npm ci

      # ESLint の実行
      - name: Run ESLint
        run: npm run lint
